# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  #registry: "ghcr.io"
  repository: "astergam/kbot"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.5-72574c0"
  os: "linux"
  arch: "amd64"

# Секція для токену TELE_TOKEN
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
  value: "NjU1MjQ2NzQ0OTpBQUZHR3k3WnREdjlpRExmdEx5OV85cDF5U0tNSTNkeU00aw=="
securityContext:
  privileged: true
