name: KBOT-CICD

on:
    push:
        branches:
        - develop

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Run test
          run: make test

        - name: 'Login to GitHub'
          uses: docker/login-action@v3
          with:
            registry: "ghcr.io"
            username: ${{ github.actor }}
            password: ${{ secrets.TELE_TOKEN }}
        
        - name: Build&Push
          env:
            APP: "kbot"
          run: make image push