name: KBOT-CICD

on:
    push:
        branches:
        - develop

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Run test
          run: make test

        - name: 'Login to GitHub'
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ secrets.USERNAME_GIT }}
            password: ${{ secrets.TOKEN_GIT }}
        
        - name: Build&Push
          env:
            APP: "kbot"
            REGISTY: ${{ secrets.USERNAME_GIT }}
          run: make image push